### ISSUE TITLE
Brak możliwości wyłączenia płatności ratalnych

### ISSUE THREAD

**Issue by polo195pl** [tpay-com/tpay-prestashop-legacy#1]
Presta 1.7.3.1 

Pomimo wyłączenia w opcjach modułu płatności ratalnych są one nadal dostępne przy wyborze kanału płatności.

**Comment by piotrjozwiak** [comment]
@polo195pl opcja płatności ratalnych służy do wyodrębniania tej metody płatności jako osobnego przycisku na stronie koszyka (o ile wartość zamówienia przekracza 300zł).
Aby wyłączyć ten kanał z wyboru listy dostępnych banków w metodzie "Zapłać przelewem online", prosimy zalogować się do panleu odbiorcy płatności i w sekcji "twoja oferta" odznaczyć pozycję 109 | Alior Raty.
Zmiana powinna wejść w życie w ciągu jednej godziny.
