### ISSUE TITLE
Błędy w templatce configuration.tpl

### ISSUE THREAD

**Issue by e-com-presta** [tpay-com/tpay-prestashop-legacy#2]
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /modules/tpay/views/templates/admin/configuration.tpl:37) in <b>/classes/controller/AdminController.php</b> on line <b>1829</b><br />

**Comment by piotrjozwiak** [comment]
@e-com-presta prosimy o sprawdzenie, czy commit 4e0610ac790548b621a8f802f5f977cab260c391 rozwiązuje wskazany problem.
