### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by bocianl** [tpay-com/tpay-prestashop-legacy#3]
Witam,
Stara wersja modułu dla PS 1.6 miała integrację z GA. W nowej wersji nie widzę takiej opcji. Czy zostanie ta opcja dodana?

**Comment by piotrjozwiak** [comment]
Witaj @bocianl 
We wcześniejszych wersjach modułu generowana była dedykowana strona sukcesu i na niej wywoływany kod Google Analytics. Ze względu na fakt iż różni sprzedawcy korzystają z różnych narzędzi analitycznych oraz innych akcji, które wywoływane są na stronie podziękowania, zdecydowaliśmy o przekierowaniu klientów na generyczną stronę, która uruchamia wszystkie moduły korzystające z zaczepu order confirmation. W związku z tym, do uruchomienia analityki Google, potrzebny jest dedykowany moduł Google Analytics do Prestashop, który wykona analizę automatycznie, na stronie podziękowania.
