### ISSUE TITLE
Problem z tpay na supercheckout od knowband

### ISSUE THREAD

**Issue by adamj240** [tpay-com/tpay-prestashop-legacy#4]
Witam
Mamy problem z modułem tpay na popularnym koszyku OPC od fimy knowband. Przy próbie realizacji zamówienia mamy błąd z informacją: Invalid checksum

Najnowsza wersja PS 1.7.8.7
Czy udało się komuś z nim poradzić?

**Comment by BanczerowskiM** [comment]
Witaj @adamj240,

komunikat "Invalid checksum" na Panelu Transakcyjnym, korzystając z modułu Tpay do platformy PrestaShop, pojawia się w dwóch przypadkach:
1. Używając starego modułu - obecna wersja to 1.7.4.
2. Gdy podane dane konfiguracyjne w module są nieprawidłowe. W tym przypadku zweryfikuj czy wpisujesz odpowiednie dane.
W polu "ID sprzedawcy" wpisz login, który używasz do logowania się do Panelu Akceptanta Tpay.
W polu "Kod bezpieczeństwa" wpisz kod bezpieczeństwa, który znajduję się w Panelu Akceptanta w zakładce Ustawienia -> Powiadomienia, w sekcji Zabezpieczenia.
Uwaga! Niektóre platformy sprzedażowe, w tym PrestaShop mają problemy z interpretacją znaków specjalnych m. in. &<>"= użycie takiego znaku może powodować
pojawienie się błędu "Nieprawidłowy kod bezpieczeństwa", dlatego zalecamy wpisanie ręczenie kodu w Panelu np. KodBezpieczensta123_ pamiętaj, aby po zmianie kodu zapisać zmiany.
