### ISSUE TITLE
Brak kompatybilności - Prestashop 8

### ISSUE THREAD

**Issue by futurowebpl** [tpay-com/tpay-prestashop-legacy#5]
Dzień dobry,

Ostatnia wersja wtyczki 1.7.4 nie jest kompatybilna z Prestashop 8.

Prośba o wydanie wersji dla Prestashop 8.

**Comment by tenszaqu** [comment]
Witam, również się podpinam pod prośbę, aktualnie nie możemy korzystać z płatności tpay.

**Comment by KamilChlodek** [comment]
Również czekamy na wtyczkę dla Prestashop 8. Parę miesięcy temu poinformowano mnie, że trwają pracę i wtyczka będzie gotowa pod koniec kwietnia.

**Comment by monterek** [comment]
Ponieważ 8.0 nie rożni sie w sposobie zarządzania płatnościami w stosunku do 1.7 to tak naprawdę wystarczy tylko edytować plik tpay.php i w wierszu 35 zmienić z:
define('TPAY_PS_17', (version_compare(_PS_VERSION_, '1.7', '>=')));
na
define('TPAY_PS_17', (version_compare(_PS_VERSION_, '8.0', '>=')));

oraz w wierszu 57 z:
        $this->ps_versions_compliancy = array('min' => '1.6', 'max' => '8.0');
na
        $this->ps_versions_compliancy = array('min' => '1.6', 'max' => '1.7');


Dodatkowo mozesz zmienić z:
        $this->version = '1.7.4';
na
        $this->version = '1.7.4.1';

Abyś w panelu miał info ze masz inna wersje niż oficjalna.

**Comment by futurowebpl** [comment]
Nie będziemy dostosowywać modułu płatności, to szalony pomysł.

Wersja wtyczki Prestashop 8.0 została opublikowana na stronie operatora płatności:
https://tpay.com/dla-developera/integracje 

Temat zostaje zamknięty.
